default: &default
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  adapter: postgresql
  username: <%= ENV.fetch("DATABASE_USERNAME") { '' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { '' } %>

development: 
  <<: *default
  database: stock_trading_development

test:
  <<: *default
  database: stock_trading_test

production:
  <<: *default
  detabase: stock_trading_production